menu = [
  { name = "Home", path = "index.md" },
  { name = "TechWriting", path = "tech/index.md" },
  { name = "WritingForFun", path = "fun/index.md" },
  { name = "FamilyStuff", path = "family/index.md" },
  { name = "AboutMe", path = "about.md" }
]
