menu = [
  { name = "Home", path = "index.md" },
  { name = "Tech", path = "tech/index.md" },
  { name = "Fun", path = "fun/index.md" },
  { name = "Family", path = "family/index.md" },
  { name = "Me", path = "about.md" }
]
