name: Build and Deploy Site

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'  # Prevent infinite loops by ignoring changes to the docs directory
      - '.github/workflows/build-site.yml'  # Ignore changes to this workflow file itself
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper Git operations
      
      - name: Setup Git identity
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Download latest Krems
        run: |
          # Get the latest release URL
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/mreider/krems/releases/latest | grep "tag_name" | cut -d '"' -f 4)
          # Download the appropriate binary for Ubuntu
          curl -L "https://github.com/mreider/krems/releases/download/${LATEST_RELEASE}/krems-linux-amd64" -o krems
          chmod +x krems
      
      - name: Build site
        run: |
          # Build the site using the latest Krems
          ./krems --build
      
      - name: Check for changes
        id: check_changes
        run: |
          git add docs
          # Check if there are any changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git commit -m "Automatically rebuild site with latest Krems"
          git push